name: Android CI

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build_android_components:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Testing ussd-library
        run: ./gradlew assembleDebug lint testDebugUnitTest -p ussd-library
      - name: Upload Testing ussd-library
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-test
          path: ussd-library/build/reports/tests/testDebugUnitTest
      - name: Upload ussd-library artifact
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-aar
          path: ussd-library/build/outputs/aar/ussd-library-debug.aar
      - name: Testing ussd-library-kotlin
        run: ./gradlew assembleDebug lint testDebugUnitTest -p ussd-library-kotlin
      - name: Upload Testing ussd-library-kotlin
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-kotlin-test
          path: ussd-library-kotlin/build/reports/tests/testDebugUnitTest
      - name: Upload ussd-library-kotlin artifact
        uses: actions/upload-artifact@v1
        with:
          name: ussd-library-kotlin-aar
          path: ussd-library-kotlin/build/outputs/aar/ussd-library-kotlin-debug.aar

  android_testing:
    name: Instrumented tests
    runs-on: macos-latest
    timeout-minutes: 25
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
      ENABLE_APP_VERSIONING: false

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
      - uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd

      - name: Generate AVD snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          arch: x86
          profile: Nexus 5X
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 5X
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew connectedCheck -p app-kotlin